- .devcontainer/devcontainer.json
- .devcontainer/scripts/post_create_command.sh
- .github/dependabot.yml
Allows setting up an entire development environment for this project inside a container without need to install any additional tool on your own machine. 
More info at: https://code.visualstudio.com/docs/devcontainers/containers
Signed-off-by: Jonathan Kilzi <jkilzi@redhat.com>
> Adds devcontainer files

- client/eslint.config.mjs
- client/package-lock.json
- client/package.json
- client/src/utils/handleLogin.ts
Add initial linting
- use eslint
- does stylelinting
- does import sorting
- adds scripts for lint and lint:fix
> Add initial linting

- server/Makefile
- server/internal/server/handlers.go
send data to /credentials instead of /api/credentials
> Fix backend path

- server/static/index.html
> Accept text response

- README.md
use host netweork when running pod
> use host netweork when running pod

- client/scripts/serve.js
- client/src/index.html
> fix autoload

- .github/workflows/build-push-images.yaml
Add new action to create the container when push in main branch
> Add new action to create the container when push in main branch

- apps/demo/src/migration-wizard/MigrationWizard.tsx
- apps/demo/src/migration-wizard/steps/prepare-migration/PrepareMigrationStep.tsx
Adding preparing migration page to the Wizard
https://github.com/user-attachments/assets/5561488a-c368-45e4-a65f-8e7d6624c59c
> Adding preparing migration page to the Wizard

- apps/demo/src/apis/responses/up-to-date.json
- apps/demo/src/migration-wizard/steps/connect/ConnectStep.tsx
Related to https://issues.redhat.com/browse/ECOPROJECT-2229
And when click "Add source" button:
> ECOPROJECT-2229: Add multiple sources in Migration UI

- apps/demo/src/migration-wizard/contexts/discovery-sources/@types/DiscoverySources.d.ts
- apps/demo/src/migration-wizard/contexts/discovery-sources/Provider.tsx
- apps/demo/src/migration-wizard/steps/connect/sources-table/SourcesTable.tsx
- apps/demo/src/migration-wizard/steps/discovery/DiscoveryStep.tsx
Related to https://issues.redhat.com/browse/ECOPROJECT-2304
https://github.com/user-attachments/assets/8267114e-8bf1-42d1-baff-7c0babffd490
> ECOPROJECT-2304: Add an option to discover a specific source

- apps/demo/src/migration-wizard/steps/connect/sources-table/empty-state/DiscoverySourceSetupModal.tsx
This PR adds the validation of the SSH-key.
> Validate the SSH key

- .github/workflows/release.yaml
Publish library as NPM package
> NO-ISSUE: Publish library as NPM package

- apps/demo/src/migration-wizard/contexts/discovery-sources/Provider.tsx
- apps/demo/src/migration-wizard/steps/connect/ConnectStep.tsx
This reverts commit c3d6196a8adaa9b234ddb7678a80332eba4e45f8.
> Revert "Adding error in UI when creating source not works well (#28)"

- apps/demo/src/migration-wizard/steps/connect/sources-table/SourcesTable.tsx
Solving problems when sources and agents don't have values.
Before changes:
After changes:
> Solving problems when sources and agents don't have values

- .github/workflows/push-to-main.yaml
Create latest agent artifact on push to main action
> Create latest agent artifact on push to main action

- .gitignore
- ci/build-deploy.sh
- ci/pr-check.sh
There are two scipts that need to be added here:
* build-deploy.sh - build and push the image to app-sre quay.io registry
* pr-check.sh - Just build the image for validation
> ECOPROJECT-2524: Add AppSRE Continues Integration scripts

- apps/agent/src/login-form/LoginForm.tsx
> ECOPROJECT-2451: Change credentials notice just to inform RO account is sufficient

- apps/demo/src/migration-wizard/MigrationWizard.tsx
- apps/demo/src/migration-wizard/steps/connect/sources-table/SourcesTable.tsx
- apps/demo/src/migration-wizard/steps/discovery/DiscoveryStep.tsx
- apps/demo/src/migration-wizard/steps/discovery/DownloadPDFButton.tsx
- apps/demo/src/migration-wizard/steps/discovery/ReportTable.tsx
Related to https://issues.redhat.com/browse/ECOPROJECT-2594
https://github.com/user-attachments/assets/f76240ed-b47b-4c53-8986-2fee38092a81
> ECOPROJECT-2594: Changes related with Download PDF in Discovery Report step

- ci/build-deploy.sh
- deploy/templates/ui-template.yml
This commit include:
* Add ui-template yaml, to be used by AppSRE
* In build-deploy.sh, allow changing MIGRATION_PLANNER_UI_IMAGE before running the script
> ECOPROJECT-2525: Add openshift templates

- apps/demo/src/apis/responses/up-to-date.json
- apps/demo/src/migration-wizard/MigrationWizard.tsx
Related with https://issues.redhat.com/browse/ECOPROJECT-2681
> ECOPROJECT-2681: When sourceSelected don't have agent we don't allow to click in the wizard steps

- apps/demo/src/migration-wizard/steps/connect/ConnectStep.tsx
- apps/demo/src/migration-wizard/steps/connect/sources-table/AgentStatusView.tsx
- apps/demo/src/migration-wizard/steps/connect/sources-table/empty-state/EmptyState.tsx
Related to https://issues.redhat.com/browse/ECOPROJECT-2676
> ECOPROJECT-2676: Changing our wording from "Add source" to "Add environment"

- apps/demo/src/migration-wizard/MigrationWizard.tsx
Related to https://issues.redhat.com/browse/ECOPROJECT-2690
> ECOPROJECT-2690: Enable next button when source become Ready without refreshing

- apps/demo/src/hooks/useAccountsAccessToken.tsx
- apps/demo/src/main/Root.tsx
Related to https://issues.redhat.com/browse/ECOPROJECT-2684
> ECOPROJECT-2684: Pass Auth Token to API requests

- packages/api-client/src/apis/index.ts
Adding GetSourceRequest, UpdateSourceRequest exports to api-client package
> Adding GetSourceRequest, UpdateSourceRequest exports to api-client package

- apps/demo/src/migration-wizard/contexts/discovery-sources/Provider.tsx
Add error handling to fix the message thrown in the UI for when creation of new source fails.
It also handles the case when creating a new source with a name that already exists.
in this case the message in the UI:
"Failed to create source. Response: "duplicated key not allowed" where "duplicated key not allowed" is the error message in the source api response .
instead of:
"Error downloading source: 400 bad request"
> Improve error handling when creating a source

- packages/api-client/src/models/Infra.ts
Update to latest API - followup
> Update to latest API - followup
